- src/bus.rs
- src/config/bus.rs
TimingParams is split to exploit the similarities between the bit timing configuration in NBTP and DBTP. Timestamping is just moved to a separate struct for now.
The validity of the parameters in the new BitTiming struct now checked when applying them instead of on construction. This prevents public fields in the struct allowing the user to skip the checks.
The divider (now called `prescaler` to better match the manual) calculation is changed to remove floating point operations.
> Enable bit timing configuration for bit-rate switched data

- mcan/Cargo.toml
In order to make `mcan` releasable in the future, it should depend on `mcan-core` through crates.io registry instead of the PATH.
> Refer to `mcan-core` via crates.io

- mcan-core/src/lib.rs
- mcan/src/bus.rs
- mcan/src/lib.rs
- mcan/src/prelude.rs
- mcan-core is missing `no_std`, so application crates for embedded targets do not compile.
- re-export `embedded-can`
- add a small prelude
- derive `Debug` for `OutOfBounds`
> Small fixes

- mcan-core/Cargo.toml
Release contains:
- fix for previously missing `#![no_std]` attribute (#8)
> Release mcan-core/0.1.1

- mcan/src/rx_dedicated_buffers.rs
- mcan/src/rx_fifo.rs
This simplifies the typical use case where the interrupt flag is not cleared without the intent to handle all messages currently in the buffer.
> Implement Iterator for received messages

- mcan/src/bus.rs
- mcan/src/interrupt.rs
- mcan/src/prelude.rs
- mcan/src/rx_dedicated_buffers.rs
- mcan/src/rx_fifo.rs
- mcan/src/tx_buffers.rs
- mcan/src/tx_event_fifo.rs
`Dyn*` traits should decrease virality of generic parameters in function signatures. Thanks to them type constraints can be more selective.
Functionality exposed previously by the `CanBus` trait and implemented by the `Can` struct was moved to `Aux` struct (previously `Internals`) in order to provide this APIs also after `Can` struct is destructured by the user.
> Introduce `Dyn*` traits + rename `Internals` to `Aux`

- mcan/src/bus.rs
- mcan/src/rx_dedicated_buffers.rs
- mcan/src/tx_buffers.rs
Previously, user could build any message and send it, regardless of the actual CAN configuration. Now, attempt to send a FD message or bitrate switched FD message with a misconfigured CAN will yield an appropriate error.
> Add validation of transmitted messages

- mcan/src/message/mod.rs
- mcan/src/message/rx.rs
- mcan/src/message/tx.rs
Previously, `MessageBuilder` allowed for creation of "remote" CAN FD messages which are not supported by CAN protocol.
> Make "FD remote frames" unrepresentable

- mcan-core/Cargo.toml
- mcan-core/src/lib.rs
MCAN uses 16-bit addressing internally. In order to validate the correctness of the `Message RAM` placement, target HAL has to provide the information about its absolute position in RAM.
> Demand `Message RAM` pointer through `Dependencies`

- mcan-core/Cargo.toml
- mcan-core/src/lib.rs
> Improve safety doc-string for `Dependencies` trait

- mcan/src/config.rs
These structs should be also constructible with sane defaults from the user code.
> Expose constructors for `CanConfig` and `BitTiming`

- mcan/src/bus.rs
I didn't check what name is most commonly used for functions like this in HALs, but I have seen both `release` and `free`.
> Allow deinitializing to get the Dependencies back

- mcan/Cargo.toml
The first actual release of the `mcan` crate.
> Release mcan/0.2.0

- mcan-core/Cargo.toml
Version 0.2.1 did not include updated README.md. Now, both mcan/0.2.0 and mcan-core/0.2.2 should have the same welcome page on `crates.io`
> Release mcan-core/0.2.2

- mcan/src/interrupt.rs
If `OwnedInterruptSet` is dropped, you cannot interact with the interrupts anymore. E.g. clearing them.
> Make OwnedInterruptSet must_use

- mcan-core/CHANGELOG.md
- mcan/CHANGELOG.md
- Add `Default` implementation for `OwnedInterruptSet` (#37)
- Add InterruptSet::is_empty (#36)
- Expand interrupt API (#34)
- *Breaking:* Refine the interrupt system (#39)
- Make `OwnedInterruptSet` `must_use` (#33)
> Release mcan/0.3.0

- Cargo.toml
- mcan/CHANGELOG.md
- mcan/src/rx_dedicated_buffers.rs
All workspace members are already edition 2021 (implying resolver 2). 
Setting it on workspace to silence warnings.
Fixed clippy recommendation regarding `filter_map`, see clippy lint `filter_map_bool_then` for details.
> Fix warnings as of rust 1.73.0

- mcan/CHANGELOG.md
- mcan/src/bus.rs
- mcan/src/reg.rs
Added initialization_mode method to DynAux trait, to enable software support for disabling of the CAN bus.
Created a new method initialization_mode in reg, similar to configuration_mode but without setting the configuration bit. While CCCR.INIT is set, message transfer from and to the CAN bus is stopped. Setting CCCR.INIT does not change any configuration register.
Exposed the initialization mode by adding the initialization_mode function to the DynAux trait, with will implement a call to the initialization_mode method in reg.
> Expose initialization mode

- mcan/CHANGELOG.md
- mcan/src/bus.rs
This change fixes some issues where watermark maximum sizes were interpreted the wrong way. Leading to watermarks clamping to the maximum value instead of disabling interrupts on overflow, as per the spec.
> Fix gte errors

- mcan/CHANGELOG.md
- mcan/Cargo.toml
- Add `Can::aux::initialization_mode` (#41)
- Fix some issues with watermark sizes for Rx FIFOs and Tx Event FIFO (#43)
- Adhere to `filter_map_bool_then` clippy lint (#42)
> Release mcan/0.4.0

- mcan/CHANGELOG.md
- mcan/src/bus.rs
- mcan/src/reg.rs
MCAN can safely be shut down by writing to the `CCCR.CSR` register
(Clock Stop Request) and then waiting for `CCCR.CSA` (Clock Stop
Acknowledge) to become high.
This will not interrupt any ongoing transmissions/receptions and is
therefore deemed the safe way to shut down the bus.
Note: It is not stated directly, but testing has shown that issuing a
stop request will only wait for the currently ongoing transmissions
and not what is queued. These messages will be sent once we enter
operational mode again.
> Implement MCAN shutdown by writing to CSR

- mcan/CHANGELOG.md
- mcan/src/bus.rs
It is useful for applications to be able to decide when to bring MCAN into operational mode. Therefore, add the option for user to finalize the configuration into initialization mode rather than operational mode directly.
> Add method to finalize config into initialization mode

- mcan/CHANGELOG.md
- mcan/Cargo.toml
- Add safe way to shutdown the bus when actively transmitting/receiving (#45)
- Add method to finalize configuration into initialization mode (#47)
- *Breaking* Update the register mappings with svd2rust 0.30.2 and form 0.10.0 (#46)
> Release mcan/0.5.0

- mcan/src/bus.rs
- mcan/src/config.rs
- mcan/src/interrupt.rs
- mcan/src/message/tx.rs
- mcan/src/messageram.rs
- mcan/src/rx_dedicated_buffers.rs
- mcan/src/rx_fifo.rs
- mcan/src/tx_buffers.rs
- mcan/src/tx_event_fifo.rs
* Elide lifetimes as suggested by `clippy::needless_lifetimes`[1]
* Fix doc list indentation warnings, `clippy::doc_lazy_continuation`[2], as appropriate
* Add `Default` implementation for `SharedMemory` as suggested by `clippy::new_without_default`[3]
[1]: https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
[2]: https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
[3]: https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
> Fix new clippy warnings from Rust 1.84.0

- mcan/CHANGELOG.md
- mcan/src/bus.rs
Checking if the bus is dominant (i.e., the RX pin value is low) can be particularly useful in scenarios where the transceiver is put into sleep mode. Some transceivers (such as TCAN1043-Q1[1]) signals wake-up by setting the RX pin (and nFAULT) to low while being in sleep mode. To accurately tell if the transceiver requests a wake-up, the RX pin state needs to be accessible from the application.
Fortunately MCAN exposes a way to read the state of the RX pin through its `TEST` register. Extend the `DynAux` trait with an additional method that reads the `RX` bit from that register.
[1]: https://www.ti.com/product/TCAN1043-Q1
> Add method to check if bus is dominant

- mcan/CHANGELOG.md
- mcan/src/bus.rs
To help when diagnosing the reason for a failed transmission, the TFQF, Tx FIFO/Queue Full, status is exposed through the DynAux trait.
> Add method to check if Tx FIFO/QUEUE is full
